# Use a lightweight JDK 17 image
FROM openjdk:17-jdk-slim

# Install necessary packages: Nginx, Certbot, fonts for Java
RUN apt-get update && apt-get install -y \
    fontconfig \
    fonts-dejavu-core \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the Gradle build directory into the container
COPY ./build/libs/*.jar app.jar

# Expose HTTP and HTTPS ports
EXPOSE 1212

# Script to start Nginx, obtain SSL certificates, and run the application
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Set the entrypoint script
ENTRYPOINT ["/docker-entrypoint.sh"]
